---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    k8s-app: siterm-agent-___REPLACEME___
  name: siterm-agent-___REPLACEME___
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: siterm-agent-___REPLACEME___
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
      labels:
        k8s-app: siterm-agent-___REPLACEME___
    spec:
      hostNetwork: true
      terminationGracePeriodSeconds: 30
      containers:
      - image: sdnsense/site-agent-sense:dev
        imagePullPolicy: "Always"
        name: siterm-agent
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        volumeMounts:
        - mountPath: /etc/dtnrm.yaml
          name: sitermagent
          subPath: sense-siterm-agent.yaml
        - mountPath: /etc/grid-security/hostcert.pem
          name: agent-hostcert
          readOnly: true
          subPath: hostcert.pem
        - mountPath: /etc/grid-security/hostkey.pem
          name: agent-hostkey
          readOnly: true
          subPath: hostkey.pem
      nodeSelector:
          kubernetes.io/hostname: ___REPLACEME___
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: sense-siterm-agent
            path: sense-siterm-agent.yaml
          name: sense-agent-___REPLACEME___
        name: sitermagent
      - name: agent-hostcert
        secret:
          secretName: sense-agent-___REPLACEME___
          items:
          - key: agent-hostcert
            path: hostcert.pem
          defaultMode: 0644
      - name: agent-hostkey
        secret:
          secretName: sense-agent-___REPLACEME___
          items:
          - key: agent-hostkey
            path: hostkey.pem
          defaultMode: 0644
status: {}
